# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58752ff8fd0b05fd0642e00eb10402ce050ac6031623978d9088c2c833059457191da4961a260e0020f4533fbb77217ce9eb87708c814971ce6398163a62c8b8

test:
  secret_key_base: 184cbaa83d695d36980049ace3773fb3367a61e12915923db17db7d0479fb0dd110959e3b7a9361331d51b444159bc9df91744bcef657c436f96991d06b23183

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
